# File generated by CompCert 3.7
# Command line: count.c -S -O0 -o annotated/count-O0.s
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	xorl	%ecx, %ecx
	xorl	%eax, %eax
.L100:
	cmpl	%ecx, %eax
	jge	.L101
# annotation: "try  loop bound: %rcx;"
	leal	1(%eax), %eax
	jmp	.L100
.L101:
	xorl	%eax, %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
