# File generated by CompCert 3.7
# Command line: pread.c -S -O0 -o annotated/pread-O0.s
	.comm	z, 4, 4
	.comm	x, 4, 4
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	z(%rip), %eax
# annotation: "L(%rax) = true"
	movl	x(%rip), %edi
	movl	z(%rip), %r10d
# annotation: "L(%rdi)= %r10 % 2 == 0"
	xorl	%edx, %edx
	xorl	%esi, %esi
# annotation: "L(%rsi)= false"
# annotation: "_P_0: %rdx % 2 == 0"
# annotation: "_Gamma_0: %rdx -> LOW, %rsi -> LOW"
.L100:
	movl	z(%rip), %edi
# annotation: "_invariant: %rdx % 2 == 0 & %rdx <= %rdi"
	movl	z(%rip), %eax
# annotation: "_Gamma: %rdx -> LOW, %rsi -> (%rdx == %rax), %rax -> LOW"
.L101:
	movl	z(%rip), %r9d
# annotation: "_invariant: %rdx <= %r9"
# annotation: "_Gamma: %rdx -> LOW"
	movl	z(%rip), %edx
	movq	%rdx, %rsi
	movq	%rsi, %rax
	testl	%eax, %eax
	leal	1(%eax), %ecx
	cmovl	%rcx, %rax
	sarl	$1, %eax
	leal	0(,%eax,2), %r11d
	subl	%r11d, %esi
	testl	%esi, %esi
	jne	.L101
	movl	x(%rip), %esi
	movl	z(%rip), %r8d
	jmp	.L100
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
