# File generated by CompCert 3.7
# Command line: variable.c -S -O0 -o annotated/variable-O0.s
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$-10, %esi
# annotation: "%rsi = int"
	movl	$98, %ecx
# annotation: "%rcx = char"
	negl	%ecx
# annotation: "%rcx = unsigned int"
	movl	$1, %r9d
# annotation: "%r9 = short"
	movabsq	$4294967296, %rax
# annotation: "%rax = long"
	movsd	.L100(%rip), %xmm1 # 3.14159265358979312
	cvtsd2ss %xmm1, %xmm2
# annotation: "%xmm2 = float"
	cvtss2sd %xmm2, %xmm0
	movsd	.L101(%rip), %xmm3 # 2.37840000000000007
	divsd	%xmm3, %xmm0
# annotation: "%xmm0 = double"
	cqto
	shrq	$59, %rdx
	leaq	0(%rax,%rdx,1), %rax
	sarq	$5, %rax
	leal	0(%eax,%esi,1), %r8d
	leal	0(%r8d,%ecx,1), %esi
	leal	0(%esi,%r9d,1), %r9d
	cvttss2si %xmm2, %ecx
	leal	0(%r9d,%ecx,1), %r8d
	cvttsd2si %xmm0, %r11d
	leal	0(%r8d,%r11d,1), %r10d
	leal	0(%r10d,%edi,1), %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
	.section	.rodata.cst8,"aM",@progbits,8
	.align	8
.L100:	.quad	0x400921fb54442d18
.L101:	.quad	0x400306f694467382
