# File generated by CompCert 3.7
# Command line: variable.c -S -O3 -o annotated/variable-O3.s
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
# annotation: "-10 = int"
# annotation: "98 = char"
# annotation: "-98 = unsigned int"
# annotation: "1 = short"
# annotation: "4294967296 = long"
# annotation: "3.14159274101257324 = float"
# annotation: "1.32088493988083289 = double"
	leal	134217625(%edi), %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
