# File generated by CompCert 3.7
# Command line: count.c -S -O0 -o annotated/count-O0.s
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	xorl	%ecx, %ecx
	xorl	%eax, %eax
.L100:
	cmpl	%ecx, %eax
	jge	.L101
.L102:
	leal	1(%eax), %eax
	jmp	.L100
.L101:
	xorl	%eax, %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
	.section	"__compcert_ais_annotations","",@note
	.ascii "# file:count.c line:5 function:main\ntry  loop "
	.byte 7,8
	.quad .L102
	.ascii "  bound: reg(\"rcx\");\n"
