# File generated by CompCert 3.7
# Command line: deadStoreElimination.c -O0 -S
	.text
	.align	16
	.globl deadStore
deadStore:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$43981, %ecx
.L100:
	nop
.L101:
	cmpl	%esi, %edi
	jle	.L102
	leal	-1(%edi), %edi
	jmp	.L101
.L102:
	leal	0(%edi,%esi,1), %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	deadStore, @function
	.size	deadStore, . - deadStore
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$2, %esi
	call	deadStore
	xorl	%eax, %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
	.section	"__compcert_ais_annotations","",@note
	.ascii "# file:deadStoreElimination.c line:3 function:deadStore\n"
	.byte 7,8
	.quad .L100
	.ascii " L(reg(\"rcx\")) = high\n"
