# File generated by CompCert 3.7
# Command line: variable.c -S -O0
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$-10, %esi
.L100:
	movl	$98, %ecx
.L101:
	negl	%ecx
.L102:
	movl	$1, %r10d
.L103:
	movabsq	$4294967296, %rax
.L104:
	movsd	.L105(%rip), %xmm1 # 3.14159265358979312
	cvtsd2ss %xmm1, %xmm3
	cvtss2sd %xmm3, %xmm0
	movsd	.L106(%rip), %xmm2 # 2.37840000000000007
	divsd	%xmm2, %xmm0
	cqto
	shrq	$59, %rdx
	leaq	0(%rax,%rdx,1), %rax
	sarq	$5, %rax
	leal	0(%eax,%esi,1), %r9d
	leal	0(%r9d,%ecx,1), %r8d
	leal	0(%r8d,%r10d,1), %r10d
	cvttss2si %xmm3, %edx
	leal	0(%r10d,%edx,1), %r11d
	cvttsd2si %xmm0, %r8d
	leal	0(%r11d,%r8d,1), %ecx
	leal	0(%ecx,%edi,1), %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
	.section	.rodata.cst8,"aM",@progbits,8
	.align	8
.L105:	.quad	0x400921fb54442d18
.L106:	.quad	0x400306f694467382
	.section	"__compcert_ais_annotations","",@note
	.ascii "# file:variable.c line:3 function:main\n"
	.byte 7,8
	.quad .L100
	.ascii " reg(\"rsi\") = int\n"
	.ascii "# file:variable.c line:5 function:main\n"
	.byte 7,8
	.quad .L101
	.ascii " reg(\"rcx\") = char\n"
	.ascii "# file:variable.c line:7 function:main\n"
	.byte 7,8
	.quad .L102
	.ascii " reg(\"rcx\") = unsigned int\n"
	.ascii "# file:variable.c line:9 function:main\n"
	.byte 7,8
	.quad .L103
	.ascii " reg(\"r10\") = short\n"
	.ascii "# file:variable.c line:11 function:main\n"
	.byte 7,8
	.quad .L104
	.ascii " reg(\"rax\") = long\n"
