# File generated by CompCert 3.7
# Command line: variable.c -S -O3
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
.L100:
.L101:
.L102:
.L103:
.L104:
	leal	134217625(%edi), %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
	.section	"__compcert_ais_annotations","",@note
	.ascii "# file:variable.c line:3 function:main\n"
	.byte 7,8
	.quad .L100
	.ascii " -10 = int\n"
	.ascii "# file:variable.c line:5 function:main\n"
	.byte 7,8
	.quad .L101
	.ascii " 98 = char\n"
	.ascii "# file:variable.c line:7 function:main\n"
	.byte 7,8
	.quad .L102
	.ascii " -98 = unsigned int\n"
	.ascii "# file:variable.c line:9 function:main\n"
	.byte 7,8
	.quad .L103
	.ascii " 1 = short\n"
	.ascii "# file:variable.c line:11 function:main\n"
	.byte 7,8
	.quad .L104
	.ascii " 4294967296 = long\n"
